title: Wellcome! # name of the site
author: Elias Ramseier # name of site's author
email: admin@methone.ch # email of site's author
url: https://methone.ch # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Personal website built with Jekyll and no-style-please theme.
permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "5kow" # put your GoatCounter name if you want to use GoatCounter analytics
# https://5kow.goatcounter.com/count
 
 # remote_theme: riggraz/no-style-please 
 # theme: no-style-please / riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

# Build settings
# markdown: kramdown

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
